name: ci

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  norminette:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: norminette
        run: |
          pip install norminette
          norminette $(find . -name "*.[ch]" | grep -v tests)

  unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: run unit tests
        run: |
          sudo apt install cmake wget
          chmod +x ./scripts/cmocka_install.sh
          sudo ./scripts/cmocka_install.sh
          sudo ldconfig
          sudo apt install libcmocka0
          make unit-tests

  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: compile cub3D
        run: make
